import './globals.css';
import Header from '@/components/Header';
import ContactSection from '@/components/ContactSection';
import Footer from '@/components/Footer';


export const metadata = {
  title: 'Your Project Title',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative min-h-screen">
        <Header />

        <main className="pt-28">
          {children}
        </main>

 
        <ContactSection />
       
        <Footer />
      </body>
    </html>
  );
}