import ContactSection from '@/components/ContactSection';
import './globals.css';
import Header from '@/components/Header'; // Adjust the import path based on your folder structure

export const metadata = {
  title: 'Your Project Title',
  description: 'Generated by create next app',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="relative min-h-screen">
        <Header />
        {/* Add padding-top to your main content so it doesn't get completely hidden behind the absolute header if you don't want it to overlap entirely */}
        <main className="pt-28">
          {children}
        </main>
        <ContactSection/>
      </body>
    </html>
  );
}